from enum import Enum


class UserRole(str, Enum):
    CITIZEN = "CITIZEN"
    EMERGENCY_OFFICER = "EMERGENCY_OFFICER"
    RESOURCE_MANAGER = "RESOURCE_MANAGER"
    VOLUNTEER = "VOLUNTEER"
    ADMIN = "ADMIN"


class ServiceStatus(str, Enum):
    OPERATIONAL = "Operational"
    DEGRADED = "Degraded"
    OUTAGE = "Outage"
    NOT_ENABLED = "Not Enabled"


class VolunteerSkill(str, Enum):
    FIRST_AID = "First Aid & CPR"
    SEARCH_AND_RESCUE = "Search & Rescue"
    MEDICAL_SUPPORT = "Medical Support (EMT/Nurse/Doctor)"
    HEAVY_DRIVING = "Emergency / Heavy Vehicle Driving"
    LOGISTICS = "Emergency Logistics & Supply"
    COMMUNICATIONS = "Radio & Field Communications"
    SHELTER_MANAGEMENT = "Shelter Coordination"
    OTHER = "General Community Support"


class VolunteerAvailability(str, Enum):
    IMMEDIATE = "Available Immediately"
    STANDBY = "Standby (Within 2 Hours)"
    SCHEDULED = "Scheduled Shifts Only"
    UNAVAILABLE = "Currently Unavailable"


class EmergencyType(str, Enum):
    FLOOD = "Flood"
    FIRE = "Fire"
    MEDICAL_EMERGENCY = "Medical Emergency"
    ROAD_ACCIDENT = "Road Accident"
    CYCLONE_STORM = "Cyclone / Storm"
    LANDSLIDE = "Landslide"
    BUILDING_COLLAPSE = "Building Collapse"
    MISSING_TRAPPED = "Missing / Trapped Person"
    OTHER = "Other"


class ReportStatus(str, Enum):
    RECEIVED = "RECEIVED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    UNDER_ASSESSMENT = "UNDER_ASSESSMENT"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    RESOLVED = "RESOLVED"
    # Backwards compatibility aliases
    VERIFIED = "VERIFIED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    PENDING = "PENDING"
    REJECTED = "REJECTED"


class ReportPriority(str, Enum):
    UNASSESSED = "UNASSESSED"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class CitizenImpactLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
    NOT_SURE = "NOT_SURE"


class EvidenceValidationStatus(str, Enum):
    VALIDATED = "VALIDATED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNAVAILABLE = "UNAVAILABLE"
    PARTIALLY_VALIDATED = "PARTIALLY_VALIDATED"
    # Display and triage aliases
    VERIFIED = "VALIDATED"
    MISMATCH = "REVIEW_REQUIRED"
    FLAGGED = "LOW_CONFIDENCE"


class VerificationStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    CORROBORATED = "CORROBORATED"
    FIELD_VERIFIED = "FIELD_VERIFIED"
    CONFLICTED = "CONFLICTED"


class EvidenceConfidenceBand(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class LocationMatchState(str, Enum):
    MATCH = "MATCH"
    NEAR_MATCH = "NEAR_MATCH"
    MISMATCH = "MISMATCH"
    UNAVAILABLE = "UNAVAILABLE"


class EvidenceFreshness(str, Enum):
    FRESH = "FRESH"
    AGING = "AGING"
    STALE = "STALE"
    UNAVAILABLE = "UNAVAILABLE"


class ReportCompleteness(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    INCOMPLETE = "INCOMPLETE"


class ReportTrustState(str, Enum):
    NORMAL = "NORMAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"


# =======================================================
# Phase B: Multi-Source Corroboration & Conflict Detection
# =======================================================

class CorroborationStatus(str, Enum):
    NO_CORROBORATION = "NO_CORROBORATION"
    PARTIALLY_CORROBORATED = "PARTIALLY_CORROBORATED"
    CORROBORATED = "CORROBORATED"
    CONFLICTED = "CONFLICTED"


class CorroborationSourceType(str, Enum):
    CITIZEN_REPORT = "CITIZEN_REPORT"
    CITIZEN_EVIDENCE = "CITIZEN_EVIDENCE"
    LLM_EXTRACTED_CITIZEN_EVIDENCE = "LLM_EXTRACTED_CITIZEN_EVIDENCE"
    SENSOR_EVENT = "SENSOR_EVENT"
    FIELD_UPDATE = "FIELD_UPDATE"
    SITUATION_INTELLIGENCE = "SITUATION_INTELLIGENCE"


class CorroborationSpatialRelationship(str, Enum):
    MATCH = "MATCH"
    NEAR_MATCH = "NEAR_MATCH"
    DISTANT = "DISTANT"
    UNAVAILABLE = "UNAVAILABLE"


class CorroborationTemporalRelationship(str, Enum):
    COINCIDENT = "COINCIDENT"
    NEAR_CONTEMPORARY = "NEAR_CONTEMPORARY"
    HISTORICAL = "HISTORICAL"
    UNAVAILABLE = "UNAVAILABLE"


class CorroborationAlignment(str, Enum):
    SUPPORTING = "SUPPORTING"
    NEUTRAL = "NEUTRAL"
    CONFLICTING = "CONFLICTING"


class EvidenceConflictCategory(str, Enum):
    SPATIAL_CONFLICT = "SPATIAL_CONFLICT"
    TEMPORAL_CONFLICT = "TEMPORAL_CONFLICT"
    EVENT_TYPE_CONFLICT = "EVENT_TYPE_CONFLICT"
    OBSERVATION_CONFLICT = "OBSERVATION_CONFLICT"
    SENSOR_REPORT_CONFLICT = "SENSOR_REPORT_CONFLICT"
    CITIZEN_REPORT_CONFLICT = "CITIZEN_REPORT_CONFLICT"
    SOURCE_STATE_CONFLICT = "SOURCE_STATE_CONFLICT"


class TimelineEventType(str, Enum):
    REPORT_RECEIVED = "REPORT_RECEIVED"
    REPORT_VIEWED = "REPORT_VIEWED"
    REPORT_ACKNOWLEDGED = "REPORT_ACKNOWLEDGED"
    CITIZEN_REPORT_MODIFIED = "CITIZEN_REPORT_MODIFIED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    STATUS_CHANGED = "STATUS_CHANGED"
    REPORT_REJECTED = "REPORT_REJECTED"
    NOTE_ADDED = "NOTE_ADDED"
    EVIDENCE_CAPTURED = "EVIDENCE_CAPTURED"
    EVIDENCE_VALIDATED = "EVIDENCE_VALIDATED"
    EVIDENCE_FLAGGED = "EVIDENCE_FLAGGED"
    CORROBORATION_EVALUATED = "CORROBORATION_EVALUATED"
    EVIDENCE_CONFLICT_DETECTED = "EVIDENCE_CONFLICT_DETECTED"
    # Phase 3 Timeline Events
    RESOURCE_CREATED = "RESOURCE_CREATED"
    RESOURCE_UPDATED = "RESOURCE_UPDATED"
    RESOURCE_QUANTITY_UPDATED = "RESOURCE_QUANTITY_UPDATED"
    RESOURCE_STATUS_CHANGED = "RESOURCE_STATUS_CHANGED"
    # Healthcare Facilities Timeline Events
    HEALTHCARE_FACILITY_CREATED = "HEALTHCARE_FACILITY_CREATED"
    HEALTHCARE_FACILITY_UPDATED = "HEALTHCARE_FACILITY_UPDATED"
    HEALTHCARE_CAPACITY_UPDATED = "HEALTHCARE_CAPACITY_UPDATED"
    HEALTHCARE_STATUS_CHANGED = "HEALTHCARE_STATUS_CHANGED"
    NEEDS_ASSESSED = "NEEDS_ASSESSED"
    AI_NEEDS_SUGGESTION_GENERATED = "AI_NEEDS_SUGGESTION_GENERATED"
    RESOURCE_MATCHING_GENERATED = "RESOURCE_MATCHING_GENERATED"
    ALLOCATION_PROPOSED = "ALLOCATION_PROPOSED"
    ALLOCATION_APPROVED = "ALLOCATION_APPROVED"
    ALLOCATION_MODIFIED = "ALLOCATION_MODIFIED"
    ALLOCATION_REJECTED = "ALLOCATION_REJECTED"
    INVENTORY_UPDATED = "INVENTORY_UPDATED"
    # Phase 4 Situation Intelligence Timeline Events
    SITUATION_CLUSTER_CREATED = "SITUATION_CLUSTER_CREATED"
    SITUATION_CLUSTER_UPDATED = "SITUATION_CLUSTER_UPDATED"
    SITUATION_ASSESSMENT_STARTED = "SITUATION_ASSESSMENT_STARTED"
    SITUATION_ASSESSMENT_GENERATED = "SITUATION_ASSESSMENT_GENERATED"
    SITUATION_ASSESSMENT_FAILED = "SITUATION_ASSESSMENT_FAILED"
    SITUATION_ASSESSMENT_REVIEWED = "SITUATION_ASSESSMENT_REVIEWED"
    SITUATION_ASSESSMENT_ACCEPTED = "SITUATION_ASSESSMENT_ACCEPTED"
    SITUATION_ASSESSMENT_MODIFIED = "SITUATION_ASSESSMENT_MODIFIED"
    SITUATION_ASSESSMENT_REJECTED = "SITUATION_ASSESSMENT_REJECTED"
    # Phase 5 Multi-Agent Orchestration Timeline Events
    ORCHESTRATION_STARTED = "ORCHESTRATION_STARTED"
    AGENT_RUN_STARTED = "AGENT_RUN_STARTED"
    AGENT_RUN_COMPLETED = "AGENT_RUN_COMPLETED"
    AGENT_RUN_FAILED = "AGENT_RUN_FAILED"
    COORDINATION_PLAN_GENERATED = "COORDINATION_PLAN_GENERATED"
    COORDINATION_PLAN_REVIEWED = "COORDINATION_PLAN_REVIEWED"
    # Phase 5 Prompt 2 Conflict Resolution Timeline Events
    CONFLICT_ANALYSIS_STARTED = "CONFLICT_ANALYSIS_STARTED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    CONFLICT_RESOLVED = "CONFLICT_RESOLVED"
    CONFLICT_ESCALATED = "CONFLICT_ESCALATED"
    CONFLICT_ANALYSIS_COMPLETED = "CONFLICT_ANALYSIS_COMPLETED"
    # Phase 5 Prompt 3 Shelter Coordination Timeline Events
    SHELTER_ANALYSIS_STARTED = "SHELTER_ANALYSIS_STARTED"
    SHELTER_EVALUATED = "SHELTER_EVALUATED"
    SHELTER_RECOMMENDED = "SHELTER_RECOMMENDED"
    SHELTER_CAPACITY_SHORTFALL = "SHELTER_CAPACITY_SHORTFALL"
    SHELTER_ANALYSIS_COMPLETED = "SHELTER_ANALYSIS_COMPLETED"
    # Phase 5 Master Timeline Events (Healthcare, Volunteer, Route, Response Plan)
    HEALTHCARE_ANALYSIS_STARTED = "HEALTHCARE_ANALYSIS_STARTED"
    HEALTHCARE_EVALUATED = "HEALTHCARE_EVALUATED"
    HEALTHCARE_FACILITY_EVALUATED = "HEALTHCARE_FACILITY_EVALUATED"
    HEALTHCARE_RECOMMENDED = "HEALTHCARE_RECOMMENDED"
    HEALTHCARE_CAPACITY_SHORTFALL = "HEALTHCARE_CAPACITY_SHORTFALL"
    HEALTHCARE_ANALYSIS_COMPLETED = "HEALTHCARE_ANALYSIS_COMPLETED"
    VOLUNTEER_ANALYSIS_STARTED = "VOLUNTEER_ANALYSIS_STARTED"
    VOLUNTEER_EVALUATED = "VOLUNTEER_EVALUATED"
    VOLUNTEER_RECOMMENDED = "VOLUNTEER_RECOMMENDED"
    VOLUNTEER_SHORTFALL = "VOLUNTEER_SHORTFALL"
    VOLUNTEER_SHORTAGE_DETECTED = "VOLUNTEER_SHORTAGE_DETECTED"
    VOLUNTEER_ANALYSIS_COMPLETED = "VOLUNTEER_ANALYSIS_COMPLETED"
    ROUTE_ANALYSIS_STARTED = "ROUTE_ANALYSIS_STARTED"
    ROUTE_EVALUATED = "ROUTE_EVALUATED"
    ROUTE_RECOMMENDED = "ROUTE_RECOMMENDED"
    TRANSPORT_SHORTFALL = "TRANSPORT_SHORTFALL"
    TRANSPORT_CAPACITY_DEFICIT = "TRANSPORT_CAPACITY_DEFICIT"
    ROUTE_ANALYSIS_COMPLETED = "ROUTE_ANALYSIS_COMPLETED"
    ACTIVE_RESPONSE_PLAN_GENERATED = "ACTIVE_RESPONSE_PLAN_GENERATED"
    ACTIVE_RESPONSE_PLAN_REVIEWED = "ACTIVE_RESPONSE_PLAN_REVIEWED"
    ACTIVE_RESPONSE_PLAN_APPROVED = "ACTIVE_RESPONSE_PLAN_APPROVED"
    ACTIVE_RESPONSE_PLAN_MODIFIED = "ACTIVE_RESPONSE_PLAN_MODIFIED"
    ACTIVE_RESPONSE_PLAN_REJECTED = "ACTIVE_RESPONSE_PLAN_REJECTED"
    # Phase 6 Live Monitoring & Change Impact Timeline Events
    MONITORING_EVENT_DETECTED = "MONITORING_EVENT_DETECTED"
    MONITORING_EVENT_DEDUPLICATED = "MONITORING_EVENT_DEDUPLICATED"
    CHANGE_IMPACT_ANALYSIS_STARTED = "CHANGE_IMPACT_ANALYSIS_STARTED"
    CHANGE_IMPACT_ANALYZED = "CHANGE_IMPACT_ANALYZED"
    PLAN_IMPACT_DETECTED = "PLAN_IMPACT_DETECTED"
    PLAN_INVALIDATION_DETECTED = "PLAN_INVALIDATION_DETECTED"
    OFFICER_ATTENTION_REQUIRED = "OFFICER_ATTENTION_REQUIRED"
    MONITORING_EVENT_ACKNOWLEDGED = "MONITORING_EVENT_ACKNOWLEDGED"
    # Phase 6.3 & 6.4 Dynamic Re-Planning & Human Approval Timeline Events
    REPLANNING_STARTED = "REPLANNING_STARTED"
    AFFECTED_AGENT_EXECUTION_STARTED = "AFFECTED_AGENT_EXECUTION_STARTED"
    AFFECTED_AGENT_EXECUTION_COMPLETED = "AFFECTED_AGENT_EXECUTION_COMPLETED"
    REVISED_PLAN_GENERATED = "REVISED_PLAN_GENERATED"
    PLAN_DIFF_GENERATED = "PLAN_DIFF_GENERATED"
    PLAN_REVIEW_REQUESTED = "PLAN_REVIEW_REQUESTED"
    PLAN_APPROVED = "PLAN_APPROVED"
    PLAN_MODIFIED = "PLAN_MODIFIED"
    PLAN_REJECTED = "PLAN_REJECTED"
    PLAN_ACTIVATED = "PLAN_ACTIVATED"
    PLAN_SUPERSEDED = "PLAN_SUPERSEDED"
    STALE_PLAN_DETECTED = "STALE_PLAN_DETECTED"
    PLAN_APPROVAL_BLOCKED = "PLAN_APPROVAL_BLOCKED"
    # Phase 6.5 Simulation / What-If Scenario Events
    SIMULATION_CREATED = "SIMULATION_CREATED"
    SIMULATION_STARTED = "SIMULATION_STARTED"
    SIMULATION_SCENARIO_ADDED = "SIMULATION_SCENARIO_ADDED"
    SIMULATION_COMPLETED = "SIMULATION_COMPLETED"
    SIMULATION_FAILED = "SIMULATION_FAILED"
    SIMULATION_DISCARDED = "SIMULATION_DISCARDED"
    SIMULATION_MARKED_STALE = "SIMULATION_MARKED_STALE"
    # Phase 8 Field Operations & Incident Execution Timeline Events
    TASK_DERIVED_FROM_PLAN = "TASK_DERIVED_FROM_PLAN"
    TASK_CREATED = "TASK_CREATED"
    TASK_APPROVED = "TASK_APPROVED"
    TASK_REJECTED = "TASK_REJECTED"
    TASK_ASSIGNED = "TASK_ASSIGNED"
    TASK_REASSIGNED = "TASK_REASSIGNED"
    TASK_ACCEPTED = "TASK_ACCEPTED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_FAILED = "TASK_FAILED"
    FIELD_UPDATE_RECORDED = "FIELD_UPDATE_RECORDED"
    RESOURCE_CONSUMED = "RESOURCE_CONSUMED"
    VEHICLE_ASSIGNED = "VEHICLE_ASSIGNED"
    VOLUNTEER_ASSIGNED = "VOLUNTEER_ASSIGNED"
    SHELTER_OPERATION_UPDATED = "SHELTER_OPERATION_UPDATED"
    HEALTHCARE_OPERATION_UPDATED = "HEALTHCARE_OPERATION_UPDATED"
    ROUTE_OPERATION_UPDATED = "ROUTE_OPERATION_UPDATED"
    INCIDENT_RESOLUTION_REQUESTED = "INCIDENT_RESOLUTION_REQUESTED"
    INCIDENT_RESOLVED = "INCIDENT_RESOLVED"
    INCIDENT_CLOSED = "INCIDENT_CLOSED"
    # Phase C Field Verification Timeline Events
    FIELD_VERIFICATION_SUBMITTED = "FIELD_VERIFICATION_SUBMITTED"
    FIELD_CONDITION_CHANGED = "FIELD_CONDITION_CHANGED"
    FIELD_OBSERVATION_RECORDED = "FIELD_OBSERVATION_RECORDED"



class SeverityLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SituationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RESPONSE_IN_PROGRESS = "RESPONSE_IN_PROGRESS"
    OPERATIONS_COMPLETED = "OPERATIONS_COMPLETED"
    OFFICER_REVIEW = "OFFICER_REVIEW"
    MONITORING = "MONITORING"
    CONTAINED = "CONTAINED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class AssessmentStatus(str, Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REVIEWED = "REVIEWED"


class HazardCategory(str, Enum):
    FIRE_EXPANSION = "Fire Expansion"
    STRUCTURAL_COLLAPSE = "Structural Collapse"
    FLOODING_WATER_LEVEL = "Rising Floodwaters"
    HAZARDOUS_MATERIALS = "Hazardous Materials"
    CASUALTIES_TRAPPED = "Casualties / Trapped Persons"
    POWER_COMM_FAILURE = "Power / Grid Failure"
    WEATHER_ESCALATION = "Weather Escalation"
    TRAFFIC_BLOCKAGE = "Access Route Blockage"
    GENERAL_SAFETY = "General Safety Hazard"


class OfficerReviewAction(str, Enum):
    ACCEPT = "ACCEPT"
    MODIFY = "MODIFY"
    REJECT = "REJECT"


class ResourceType(str, Enum):
    WATER = "Water"
    FOOD = "Food"
    MEDICINE = "Medicine"
    FIRST_AID = "First Aid"
    MEDICAL_EQUIPMENT = "Medical Equipment"
    RESCUE_EQUIPMENT = "Rescue Equipment"
    PROTECTIVE_EQUIPMENT = "Protective Equipment"
    BLANKETS = "Blankets"
    CLOTHING = "Clothing"
    GENERATOR = "Generator"
    FUEL = "Fuel"
    COMMUNICATION_EQUIPMENT = "Communication Equipment"
    TRANSPORT = "Transport"
    SHELTER = "Shelter"
    HEALTHCARE = "Healthcare"
    OTHER = "Other"

    @classmethod
    def _missing_(cls, value):
        if isinstance(value, str):
            val_norm = value.strip().lower()
            if val_norm in ["medical", "medicine", "med"]:
                return cls.MEDICINE
            for member in cls:
                if member.value.lower() == val_norm or member.name.lower() == val_norm:
                    return member
        return None


class ResourceStatus(str, Enum):
    AVAILABLE = "AVAILABLE"
    PARTIALLY_AVAILABLE = "PARTIALLY_AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class ResourceCondition(str, Enum):
    GOOD = "GOOD"
    LIMITED = "LIMITED"
    DAMAGED = "DAMAGED"


class NeedUrgency(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AllocationStatus(str, Enum):
    PROPOSED = "PROPOSED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISPATCHED = "DISPATCHED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


# Phase 5 Multi-Agent Coordination Enums
class AgentName(str, Enum):
    NEEDS_AGENT = "needs_agent"
    PRIORITY_AGENT = "priority_agent"
    RESOURCE_COORDINATION_AGENT = "resource_agent"
    CONFLICT_RESOLUTION_AGENT = "conflict_agent"
    SHELTER_AGENT = "shelter_agent"
    HEALTHCARE_AGENT = "healthcare_agent"
    VOLUNTEER_AGENT = "volunteer_agent"
    ROUTE_AGENT = "route_agent"
    REPLANNING_AGENT = "replanning_agent"


class ConflictType(str, Enum):
    RESOURCE_SHORTAGE = "RESOURCE_SHORTAGE"
    COMPETING_RESOURCE_DEMAND = "COMPETING_RESOURCE_DEMAND"
    INSUFFICIENT_QUANTITY = "INSUFFICIENT_QUANTITY"
    RESOURCE_UNAVAILABLE = "RESOURCE_UNAVAILABLE"
    RESOURCE_UNFIT = "RESOURCE_UNFIT"
    RESOURCE_STATUS_CONFLICT = "RESOURCE_STATUS_CONFLICT"
    GEOGRAPHIC_MISMATCH = "GEOGRAPHIC_MISMATCH"
    PRIORITY_CONFLICT = "PRIORITY_CONFLICT"
    NEED_RESOURCE_MISMATCH = "NEED_RESOURCE_MISMATCH"
    ALLOCATION_OVERLAP = "ALLOCATION_OVERLAP"
    NO_FEASIBLE_ALLOCATION = "NO_FEASIBLE_ALLOCATION"
    DUPLICATE_RECOMMENDATION = "DUPLICATE_RECOMMENDATION"
    # Cross-domain conflict categories
    RESOURCE_TRANSPORT_MISMATCH = "RESOURCE_TRANSPORT_MISMATCH"
    HEALTHCARE_TRANSPORT_MISMATCH = "HEALTHCARE_TRANSPORT_MISMATCH"
    VOLUNTEER_SKILL_CONFLICT = "VOLUNTEER_SKILL_CONFLICT"
    VOLUNTEER_AVAILABILITY_CONFLICT = "VOLUNTEER_AVAILABILITY_CONFLICT"
    SHELTER_CAPACITY_CONFLICT = "SHELTER_CAPACITY_CONFLICT"
    ROUTE_ROAD_BLOCKAGE = "ROUTE_ROAD_BLOCKAGE"
    UNKNOWN_CONFLICT = "UNKNOWN_CONFLICT"


class ShelterConflictType(str, Enum):
    SHELTER_CAPACITY_SHORTAGE = "SHELTER_CAPACITY_SHORTAGE"
    SHELTER_FULL = "SHELTER_FULL"
    SHELTER_UNAVAILABLE = "SHELTER_UNAVAILABLE"
    SHELTER_CLOSED = "SHELTER_CLOSED"
    SHELTER_DATA_CONFLICT = "SHELTER_DATA_CONFLICT"
    SHELTER_ACCESSIBILITY_CONFLICT = "SHELTER_ACCESSIBILITY_CONFLICT"
    SHELTER_DISTANCE_CONFLICT = "SHELTER_DISTANCE_CONFLICT"
    SHELTER_SUITABILITY_CONFLICT = "SHELTER_SUITABILITY_CONFLICT"
    NO_FEASIBLE_SHELTER = "NO_FEASIBLE_SHELTER"
    POPULATION_DATA_UNAVAILABLE = "POPULATION_DATA_UNAVAILABLE"
    SHELTER_NOT_REQUIRED = "SHELTER_NOT_REQUIRED"


class HealthcareConflictType(str, Enum):
    HEALTHCARE_CAPACITY_SHORTAGE = "HEALTHCARE_CAPACITY_SHORTAGE"
    NO_FEASIBLE_FACILITY = "NO_FEASIBLE_FACILITY"
    ICU_UNAVAILABLE = "ICU_UNAVAILABLE"
    OXYGEN_UNAVAILABLE = "OXYGEN_UNAVAILABLE"
    TRAUMA_INCAPABLE = "TRAUMA_INCAPABLE"
    FACILITY_UNAVAILABLE = "FACILITY_UNAVAILABLE"
    FACILITY_FULL = "FACILITY_FULL"
    FACILITY_DATA_CONFLICT = "FACILITY_DATA_CONFLICT"
    CASUALTY_DATA_UNAVAILABLE = "CASUALTY_DATA_UNAVAILABLE"
    MEDICAL_NOT_REQUIRED = "MEDICAL_NOT_REQUIRED"


class VolunteerConflictType(str, Enum):
    VOLUNTEER_SHORTAGE = "VOLUNTEER_SHORTAGE"
    SKILL_MISMATCH = "SKILL_MISMATCH"
    CERTIFICATION_REQUIRED = "CERTIFICATION_REQUIRED"
    VOLUNTEER_UNAVAILABLE = "VOLUNTEER_UNAVAILABLE"
    DUPLICATE_ASSIGNMENT = "DUPLICATE_ASSIGNMENT"
    GEOGRAPHIC_MISMATCH = "GEOGRAPHIC_MISMATCH"
    NO_FEASIBLE_VOLUNTEER = "NO_FEASIBLE_VOLUNTEER"
    VOLUNTEER_NOT_REQUIRED = "VOLUNTEER_NOT_REQUIRED"


class RouteConflictType(str, Enum):
    NO_VEHICLE_AVAILABLE = "NO_VEHICLE_AVAILABLE"
    INSUFFICIENT_TRANSPORT_CAPACITY = "INSUFFICIENT_TRANSPORT_CAPACITY"
    BLOCKED_ROUTE = "BLOCKED_ROUTE"
    DESTINATION_UNREACHABLE = "DESTINATION_UNREACHABLE"
    VEHICLE_UNAVAILABLE = "VEHICLE_UNAVAILABLE"
    VEHICLE_INCOMPATIBLE = "VEHICLE_INCOMPATIBLE"
    TRANSPORT_NOT_REQUIRED = "TRANSPORT_NOT_REQUIRED"


class ResolutionStrategy(str, Enum):
    PRIORITY_FIRST = "PRIORITY_FIRST"
    PARTIAL_ALLOCATION = "PARTIAL_ALLOCATION"
    MULTI_SOURCE_SPLIT = "MULTI_SOURCE_SPLIT"
    ALTERNATIVE_RESOURCE = "ALTERNATIVE_RESOURCE"
    DEFER_LOW_PRIORITY = "DEFER_LOW_PRIORITY"
    UNRESOLVED_ESCALATION = "UNRESOLVED_ESCALATION"
    NO_FEASIBLE_RESOLUTION = "NO_FEASIBLE_RESOLUTION"


class ConflictStatus(str, Enum):
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    ESCALATED = "ESCALATED"


class AgentRunStatus(str, Enum):
    NOT_REQUIRED = "NOT_REQUIRED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    FALLBACK = "FALLBACK"


class CoordinationPlanStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_OFFICER_REVIEW = "PENDING_OFFICER_REVIEW"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    EXECUTED = "EXECUTED"
    SIMULATION_RESULT = "SIMULATION_RESULT"


class PlanReviewAction(str, Enum):
    APPROVE = "APPROVE"
    MODIFY = "MODIFY"
    REJECT = "REJECT"


class DiffChangeType(str, Enum):
    ADDED = "ADDED"
    REMOVED = "REMOVED"
    CHANGED = "CHANGED"
    UNCHANGED = "UNCHANGED"


# Phase 6 Live Monitoring & Unified Event Detection Enums
class MonitoringEventType(str, Enum):
    # Citizen Reports
    REPORT_CREATED = "REPORT_CREATED"
    REPORT_STATUS_CHANGED = "REPORT_STATUS_CHANGED"
    REPORT_PRIORITY_CHANGED = "REPORT_PRIORITY_CHANGED"
    REPORT_TYPE_CHANGED = "REPORT_TYPE_CHANGED"
    REPORT_LOCATION_CHANGED = "REPORT_LOCATION_CHANGED"
    REPORT_ACKNOWLEDGED = "REPORT_ACKNOWLEDGED"
    REPORT_REJECTED = "REPORT_REJECTED"
    REPORT_RESOLVED = "REPORT_RESOLVED"

    # Situation Intelligence
    SITUATION_CREATED = "SITUATION_CREATED"
    SITUATION_MEMBERSHIP_CHANGED = "SITUATION_MEMBERSHIP_CHANGED"
    SITUATION_SEVERITY_CHANGED = "SITUATION_SEVERITY_CHANGED"
    SITUATION_CONFIDENCE_CHANGED = "SITUATION_CONFIDENCE_CHANGED"
    SITUATION_LOCATION_CHANGED = "SITUATION_LOCATION_CHANGED"
    SITUATION_STATUS_CHANGED = "SITUATION_STATUS_CHANGED"

    # Resource Inventory
    RESOURCE_CREATED = "RESOURCE_CREATED"
    RESOURCE_QUANTITY_INCREASED = "RESOURCE_QUANTITY_INCREASED"
    RESOURCE_QUANTITY_DECREASED = "RESOURCE_QUANTITY_DECREASED"
    RESOURCE_QUANTITY_CHANGED = "RESOURCE_QUANTITY_CHANGED"
    RESOURCE_STATUS_CHANGED = "RESOURCE_STATUS_CHANGED"
    RESOURCE_CONDITION_CHANGED = "RESOURCE_CONDITION_CHANGED"
    RESOURCE_LOCATION_CHANGED = "RESOURCE_LOCATION_CHANGED"
    RESOURCE_ALLOCATED = "RESOURCE_ALLOCATED"
    RESOURCE_RELEASED = "RESOURCE_RELEASED"

    # Shelter Facilities
    SHELTER_CAPACITY_CHANGED = "SHELTER_CAPACITY_CHANGED"
    SHELTER_OCCUPANCY_CHANGED = "SHELTER_OCCUPANCY_CHANGED"
    SHELTER_STATUS_CHANGED = "SHELTER_STATUS_CHANGED"
    SHELTER_UNAVAILABLE = "SHELTER_UNAVAILABLE"
    SHELTER_AVAILABLE = "SHELTER_AVAILABLE"

    # Healthcare Facilities
    HEALTHCARE_CAPACITY_CHANGED = "HEALTHCARE_CAPACITY_CHANGED"
    HEALTHCARE_STATUS_CHANGED = "HEALTHCARE_STATUS_CHANGED"
    HEALTHCARE_TRAUMA_CHANGED = "HEALTHCARE_TRAUMA_CHANGED"
    HEALTHCARE_FACILITY_UNAVAILABLE = "HEALTHCARE_FACILITY_UNAVAILABLE"
    HEALTHCARE_FACILITY_AVAILABLE = "HEALTHCARE_FACILITY_AVAILABLE"

    # Volunteers & Personnel
    VOLUNTEER_AVAILABILITY_CHANGED = "VOLUNTEER_AVAILABILITY_CHANGED"
    VOLUNTEER_STATUS_CHANGED = "VOLUNTEER_STATUS_CHANGED"
    VOLUNTEER_SKILL_CHANGED = "VOLUNTEER_SKILL_CHANGED"
    VOLUNTEER_ASSIGNMENT_CHANGED = "VOLUNTEER_ASSIGNMENT_CHANGED"

    # Transport / Fleet & Routes
    TRANSPORT_AVAILABILITY_CHANGED = "TRANSPORT_AVAILABILITY_CHANGED"
    TRANSPORT_STATUS_CHANGED = "TRANSPORT_STATUS_CHANGED"
    TRANSPORT_ASSIGNMENT_CHANGED = "TRANSPORT_ASSIGNMENT_CHANGED"
    ROUTE_STATUS_CHANGED = "ROUTE_STATUS_CHANGED"
    ROUTE_OBSTRUCTION_CHANGED = "ROUTE_OBSTRUCTION_CHANGED"

    # Field Operations & Response Tasks
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_FAILED = "TASK_FAILED"
    TASK_COMPLETED = "TASK_COMPLETED"

    # Officer Decisions & Plan Lifecycles
    OFFICER_SEVERITY_OVERRIDDEN = "OFFICER_SEVERITY_OVERRIDDEN"
    OFFICER_PLAN_APPROVED = "OFFICER_PLAN_APPROVED"
    OFFICER_PLAN_MODIFIED = "OFFICER_PLAN_MODIFIED"
    OFFICER_PLAN_REJECTED = "OFFICER_PLAN_REJECTED"
    PLAN_ACTIVATED = "PLAN_ACTIVATED"
    PLAN_MODIFIED = "PLAN_MODIFIED"
    PLAN_REJECTED = "PLAN_REJECTED"
    PLAN_SUPERSEDED = "PLAN_SUPERSEDED"

    # Simulated Sensor Events & Thresholds
    SENSOR_THRESHOLD_BREACHED = "SENSOR_THRESHOLD_BREACHED"
    SENSOR_READING_RECORDED = "SENSOR_READING_RECORDED"
    SENSOR_RECOVERED = "SENSOR_RECOVERED"
    SENSOR_STATUS_CHANGED = "SENSOR_STATUS_CHANGED"
    SENSOR_DATA_STALE = "SENSOR_DATA_STALE"

    # Operational Capacity & Bottlenecks
    CRITICAL_RESOURCE_BOTTLENECK = "CRITICAL_RESOURCE_BOTTLENECK"


class EventSourceType(str, Enum):
    CITIZEN_REPORT = "CITIZEN_REPORT"
    SITUATION_INTELLIGENCE = "SITUATION_INTELLIGENCE"
    RESOURCE_INVENTORY = "RESOURCE_INVENTORY"
    SHELTER_FACILITY = "SHELTER_FACILITY"
    HEALTHCARE_FACILITY = "HEALTHCARE_FACILITY"
    VOLUNTEER_NETWORK = "VOLUNTEER_NETWORK"
    TRANSPORT_FLEET = "TRANSPORT_FLEET"
    ROUTE_NETWORK = "ROUTE_NETWORK"
    OFFICER_DECISION = "OFFICER_DECISION"
    SIMULATED_SENSOR = "SIMULATED_SENSOR"
    SYSTEM = "SYSTEM"


# --- Sensor Network & IoT Simulation Enums ---
class SensorType(str, Enum):
    WATER_LEVEL = "WATER_LEVEL"
    RAINFALL = "RAINFALL"
    TEMPERATURE = "TEMPERATURE"
    SMOKE_AIR_QUALITY = "SMOKE_AIR_QUALITY"
    AQI = "AQI"


class SensorStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    INACTIVE = "INACTIVE"


class SensorReadingSource(str, Enum):
    MANUAL_SIMULATION = "MANUAL_SIMULATION"
    LIVE_SIMULATION = "LIVE_SIMULATION"


class SensorAlertStatus(str, Enum):
    ACTIVE_BREACH = "ACTIVE_BREACH"
    RESOLVED_RECOVERED = "RESOLVED_RECOVERED"


class SimulationTrend(str, Enum):
    RISING = "RISING"
    FALLING = "FALLING"
    FLUCTUATING = "FLUCTUATING"


class EventStatus(str, Enum):
    DETECTED = "DETECTED"
    ANALYZING = "ANALYZING"
    ANALYZED = "ANALYZED"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"


class ImpactLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PlanValidityStatus(str, Enum):
    UNAFFECTED = "UNAFFECTED"
    POTENTIALLY_AFFECTED = "POTENTIALLY_AFFECTED"
    INVALIDATED = "INVALIDATED"
    REQUIRES_OFFICER_REVIEW = "REQUIRES_OFFICER_REVIEW"


class OperationalDomain(str, Enum):
    RESOURCE = "RESOURCE"
    SHELTER = "SHELTER"
    HEALTHCARE = "HEALTHCARE"
    VOLUNTEER = "VOLUNTEER"
    TRANSPORT = "TRANSPORT"
    ROUTE = "ROUTE"
    SITUATION = "SITUATION"
    CONFLICT = "CONFLICT"


# ==========================================
# Phase 7: Event-Driven Notification Enums
# ==========================================

class NotificationChannel(str, Enum):
    IN_APP = "IN_APP"
    WHATSAPP = "WHATSAPP"
    SMS = "SMS"
    WEB_PUSH = "WEB_PUSH"


class NotificationDeliveryStatus(str, Enum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    SENDING = "SENDING"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    UNDELIVERED = "UNDELIVERED"
    READ = "READ"
    FAILED = "FAILED"
    NOT_CONFIGURED = "NOT_CONFIGURED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


class NotificationCategory(str, Enum):
    CITIZEN_REPORT = "CITIZEN_REPORT"
    SITUATION = "SITUATION"
    COORDINATION_PLAN = "COORDINATION_PLAN"
    RESOURCE_LOGISTICS = "RESOURCE_LOGISTICS"
    SHELTER_OPS = "SHELTER_OPS"
    HEALTHCARE_OPS = "HEALTHCARE_OPS"
    VOLUNTEER_OPS = "VOLUNTEER_OPS"
    TRANSPORT_ROUTE = "TRANSPORT_ROUTE"
    LIVE_MONITORING = "LIVE_MONITORING"
    DYNAMIC_REPLANNING = "DYNAMIC_REPLANNING"
    WHAT_IF_SIMULATION = "WHAT_IF_SIMULATION"
    FIELD_OPERATIONS = "FIELD_OPERATIONS"


class NotificationSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ==========================================
# Phase 8: Field Operations & Execution Enums
# ==========================================

class ResponseTaskStatus(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"


class TaskType(str, Enum):
    RESOURCE_DELIVERY = "RESOURCE_DELIVERY"
    SHELTER_ACTIVATION = "SHELTER_ACTIVATION"
    PATIENT_EVACUATION = "PATIENT_EVACUATION"
    SEARCH_AND_RESCUE = "SEARCH_AND_RESCUE"
    ROUTE_CLEARANCE = "ROUTE_CLEARANCE"
    GENERAL_FIELD_OPERATION = "GENERAL_FIELD_OPERATION"


class FieldUpdateType(str, Enum):
    ARRIVED = "ARRIVED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_BLOCKED = "TASK_BLOCKED"
    TASK_FAILED = "TASK_FAILED"
    RESOURCE_CONSUMED = "RESOURCE_CONSUMED"
    RESOURCE_DAMAGED = "RESOURCE_DAMAGED"
    ROUTE_BLOCKED = "ROUTE_BLOCKED"
    MEDICAL_CONDITION_CHANGED = "MEDICAL_CONDITION_CHANGED"
    ADDITIONAL_HELP_REQUIRED = "ADDITIONAL_HELP_REQUIRED"
    SHELTER_CAPACITY_CHANGED = "SHELTER_CAPACITY_CHANGED"
    VEHICLE_UNAVAILABLE = "VEHICLE_UNAVAILABLE"
    TEAM_UNAVAILABLE = "TEAM_UNAVAILABLE"
    OTHER_OPERATIONAL_CHANGE = "OTHER_OPERATIONAL_CHANGE"


# ==========================================
# Phase C: Field Verification & Evolution Timeline Enums
# ==========================================

class FieldVerificationStatus(str, Enum):
    FIELD_VERIFIED = "FIELD_VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    NOT_FOUND = "NOT_FOUND"
    CONDITION_CHANGED = "CONDITION_CHANGED"
    UNABLE_TO_VERIFY = "UNABLE_TO_VERIFY"


class FieldObservationCategory(str, Enum):
    INCIDENT_CONFIRMED = "INCIDENT_CONFIRMED"
    INCIDENT_NOT_FOUND = "INCIDENT_NOT_FOUND"
    SEVERITY_CHANGED = "SEVERITY_CHANGED"
    WATER_LEVEL_CHANGED = "WATER_LEVEL_CHANGED"
    FIRE_SPREADING = "FIRE_SPREADING"
    ROAD_BLOCKED = "ROAD_BLOCKED"
    ROAD_CLEAR = "ROAD_CLEAR"
    SHELTER_ACCESSIBLE = "SHELTER_ACCESSIBLE"
    SHELTER_INACCESSIBLE = "SHELTER_INACCESSIBLE"
    MEDICAL_NEED_OBSERVED = "MEDICAL_NEED_OBSERVED"
    RESOURCE_SHORTAGE_OBSERVED = "RESOURCE_SHORTAGE_OBSERVED"
    CONDITION_UNKNOWN = "CONDITION_UNKNOWN"


class IncidentEvolutionCategory(str, Enum):
    REPORT = "REPORT"
    EVIDENCE = "EVIDENCE"
    SENSOR = "SENSOR"
    CORROBORATION = "CORROBORATION"
    CONFLICT = "CONFLICT"
    FIELD_VERIFICATION = "FIELD_VERIFICATION"
    OFFICER_ACTION = "OFFICER_ACTION"
    RESPONSE_PLAN = "RESPONSE_PLAN"
    FIELD_TASK = "FIELD_TASK"
    REPLANNING = "REPLANNING"
    RESOLUTION = "RESOLUTION"


# ==========================================
# Phase D: Sensor Health & Stale Data Enums
# ==========================================

class SensorReportingState(str, Enum):
    NEVER_REPORTED = "NEVER_REPORTED"
    HEALTHY = "HEALTHY"
    STALE = "STALE"
    INACTIVE = "INACTIVE"
    UNAVAILABLE = "UNAVAILABLE"


class SensorHealthState(str, Enum):
    HEALTHY = "HEALTHY"
    STALE = "STALE"
    INACTIVE = "INACTIVE"
    NEVER_REPORTED = "NEVER_REPORTED"
    UNAVAILABLE = "UNAVAILABLE"
    IN_ALERT = "IN_ALERT"


# ==========================================
# Phase D: Resource Bottleneck Intelligence
# ==========================================

class BottleneckType(str, Enum):
    RESOURCE_SHORTAGE = "RESOURCE_SHORTAGE"
    ALLOCATION_CONTENTION = "ALLOCATION_CONTENTION"
    HIGH_UTILIZATION = "HIGH_UTILIZATION"
    NO_ELIGIBLE_RESOURCE = "NO_ELIGIBLE_RESOURCE"
    LOCATION_CONSTRAINT = "LOCATION_CONSTRAINT"
    CAPABILITY_CONSTRAINT = "CAPABILITY_CONSTRAINT"
    TASK_DEPENDENCY = "TASK_DEPENDENCY"
    TRANSPORT_CONSTRAINT = "TRANSPORT_CONSTRAINT"
    STALE_RESOURCE_STATE = "STALE_RESOURCE_STATE"


class BottleneckSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ==========================================
# Phase 1: Live Citizen Safety Guidance & Web Push
# ==========================================

class GuidanceApprovalState(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    MODIFIED = "MODIFIED"
    REJECTED = "REJECTED"
    AUTO_PUBLISHED = "AUTO_PUBLISHED"


class DestinationType(str, Enum):
    SHELTER = "SHELTER"
    HEALTHCARE = "HEALTHCARE"
    POLICE = "POLICE"
    FIRE_STATION = "FIRE_STATION"
    BUS_STATION = "BUS_STATION"
    EMERGENCY_ASSISTANCE_POINT = "EMERGENCY_ASSISTANCE_POINT"
    SAFE_ASSEMBLY_AREA = "SAFE_ASSEMBLY_AREA"
    OTHER = "OTHER"


class RouteStatus(str, Enum):
    CALCULATED = "CALCULATED"
    ROUTE_UNAVAILABLE = "ROUTE_UNAVAILABLE"
    ROUTE_UNSAFE = "ROUTE_UNSAFE"
    RESTRICTED = "RESTRICTED"
    ROUTE_PROVIDER_ERROR = "ROUTE_PROVIDER_ERROR"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class PushSubscriptionStatus(str, Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    UNSUBSCRIBED = "UNSUBSCRIBED"
    INVALID = "INVALID"


class SafetyNotificationType(str, Enum):
    SAFETY_GUIDANCE_READY = "SAFETY_GUIDANCE_READY"
    SAFETY_GUIDANCE_UPDATED = "SAFETY_GUIDANCE_UPDATED"
    ROUTE_UPDATED = "ROUTE_UPDATED"
    DESTINATION_UPDATED = "DESTINATION_UPDATED"
    ROUTE_UNAVAILABLE = "ROUTE_UNAVAILABLE"
    HAZARD_WARNING = "HAZARD_WARNING"
    EVACUATION_GUIDANCE_APPROVED = "EVACUATION_GUIDANCE_APPROVED"
    GUIDANCE_EXPIRED = "GUIDANCE_EXPIRED"
    REPORT_REJECTED = "REPORT_REJECTED"
    REPORT_ACCEPTED = "REPORT_ACCEPTED"


class GuidanceStatus(str, Enum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    STALE = "STALE"
    REJECTED_BY_OFFICER = "REJECTED_BY_OFFICER"








