from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from app.models.enums import (
    MonitoringEventType,
    EventSourceType,
    EventStatus,
    ImpactLevel,
    PlanValidityStatus,
    OperationalDomain,
    AgentName,
    SeverityLevel,
)


class MonitoringEvent(BaseModel):
    """
    Canonical normalized monitoring event document stored in `monitoring_events`.
    Represents a discrete, deterministic operational state change.
    """
    event_id: str
    event_type: MonitoringEventType
    source_type: EventSourceType
    source_id: str
    situation_id: Optional[str] = None
    coordination_plan_id: Optional[str] = None
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    effective_at: datetime = Field(default_factory=datetime.utcnow)
    severity: SeverityLevel = SeverityLevel.MEDIUM
    previous_state: Dict[str, Any] = Field(default_factory=dict)
    new_state: Dict[str, Any] = Field(default_factory=dict)
    changed_fields: List[str] = Field(default_factory=list)
    location: Optional[Dict[str, Any]] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    correlation_id: Optional[str] = None
    event_fingerprint: str
    is_simulation: bool = False
    actor_id: Optional[str] = None
    actor_name: Optional[str] = None
    actor_role: Optional[str] = None
    confidence: float = Field(ge=0.0, le=1.0, default=1.0)
    status: EventStatus = EventStatus.DETECTED
    impact_level: ImpactLevel = ImpactLevel.NONE
    resolved_at: Optional[datetime] = None
    resolved_by_id: Optional[str] = None
    resolved_by_name: Optional[str] = None
    resolution_reason: Optional[str] = None
    resolved_in_plan_id: Optional[str] = None
    resolved_in_plan_version: Optional[int] = None
    remediation_status: Optional[str] = None


class ChangeImpactResult(BaseModel):
    """
    Authoritative impact assessment result generated by the ChangeImpactAnalyzer.
    Stored in `change_impacts`.
    """
    impact_id: str
    event_id: str
    situation_id: Optional[str] = None
    coordination_plan_id: Optional[str] = None
    impact_level: ImpactLevel = ImpactLevel.NONE
    plan_status: PlanValidityStatus = PlanValidityStatus.UNAFFECTED
    changed_entity: str
    changed_fields: List[str] = Field(default_factory=list)
    previous_state: Dict[str, Any] = Field(default_factory=dict)
    new_state: Dict[str, Any] = Field(default_factory=dict)
    affected_domains: List[OperationalDomain] = Field(default_factory=list)
    affected_agents: List[AgentName] = Field(default_factory=list)
    dependency_chain: List[AgentName] = Field(default_factory=list)
    affected_plan_components: List[str] = Field(default_factory=list)
    violated_constraints: List[str] = Field(default_factory=list)
    shortfalls: Dict[str, float] = Field(default_factory=dict)
    officer_attention_required: bool = False
    explanation: str
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)
    acknowledged_at: Optional[datetime] = None
    acknowledged_by_id: Optional[str] = None
    acknowledged_by_name: Optional[str] = None
    resolved_at: Optional[datetime] = None
    resolved_by_id: Optional[str] = None
    resolved_by_name: Optional[str] = None
    resolution_reason: Optional[str] = None
    resolved_in_plan_id: Optional[str] = None
    resolved_in_plan_version: Optional[int] = None
    remediation_status: Optional[str] = None


class PaginatedMonitoringEventsResponse(BaseModel):
    """
    Paginated list of monitoring events.
    """
    items: List[MonitoringEvent]
    total_count: int
    page: int
    limit: int
    total_pages: int


class MonitoringStatsResponse(BaseModel):
    """
    Real-time KPI telemetry summary for Live Monitoring dashboard.
    """
    total_events: int = 0
    active_alerts: int = 0
    critical_impacts: int = 0
    high_impacts: int = 0
    invalidated_plans: int = 0
    plans_requiring_review: int = 0
    impacted_operations_count: int = 0
    unacknowledged_events: int = 0
    acknowledged_events: int = 0
    resolved_events: int = 0
    domain_breakdown: Dict[str, int] = Field(default_factory=dict)


class AcknowledgeEventRequest(BaseModel):
    notes: Optional[str] = None


class AcknowledgeEventResponse(BaseModel):
    success: bool
    event_id: str
    status: EventStatus
    acknowledged_at: datetime
    acknowledged_by_name: str
    message: str


# =========================================================================
# PHASE 6.3 & 6.4 DYNAMIC RE-PLANNING & HUMAN APPROVAL MODELS
# =========================================================================

class PlanComponentDiffItem(BaseModel):
    """
    Detailed difference record for a specific plan component between plan versions.
    """
    category: str  # "Resource", "Shelter", "Healthcare", "Volunteer", "Transport", "Route", "Conflict"
    entity_id: str
    entity_name: str
    diff_type: str  # "ADDED", "REMOVED", "CHANGED", "UNCHANGED"
    previous_value: Optional[Any] = None
    new_value: Optional[Any] = None
    reason: Optional[str] = None
    requires_officer_attention: bool = False


class PlanDiffResult(BaseModel):
    """
    Deterministic comparison summary between previous response plan and revised response plan.
    """
    previous_plan_id: str
    previous_version: int
    new_plan_id: str
    new_version: int
    summary: str
    items: List[PlanComponentDiffItem] = Field(default_factory=list)
    affected_domains: List[OperationalDomain] = Field(default_factory=list)
    affected_agents: List[AgentName] = Field(default_factory=list)
    has_conflicts: bool = False
    is_material_change: bool = True
    generated_at: datetime = Field(default_factory=datetime.utcnow)


class ReplanningTriggerMetadata(BaseModel):
    """
    Lineage metadata linking a revised Coordination Plan to its triggering event and impact.
    """
    trigger_event_id: str
    impact_id: str
    previous_plan_id: str
    previous_version: int
    reasons: List[str] = Field(default_factory=list)
    material_change: bool = True


class PlanApprovalRequest(BaseModel):
    """
    Payload sent by Emergency Officer to approve and activate a revised response plan.
    """
    officer_notes: Optional[str] = None
    expected_state_fingerprint: Optional[str] = None


class PlanModifyRequest(BaseModel):
    """
    Payload sent by Emergency Officer to modify operational values in a revised response plan.
    """
    notes: Optional[str] = None
    modified_needs: Optional[List[Dict[str, Any]]] = None
    modified_allocations: Optional[List[Dict[str, Any]]] = None
    modified_shelters: Optional[List[Dict[str, Any]]] = None
    modified_facilities: Optional[List[Dict[str, Any]]] = None
    modified_volunteers: Optional[List[Dict[str, Any]]] = None
    modified_transports: Optional[List[Dict[str, Any]]] = None
    modified_routes: Optional[List[Dict[str, Any]]] = None


class PlanRejectRequest(BaseModel):
    """
    Payload sent by Emergency Officer to reject a revised response plan.
    """
    rejection_reason: str
    officer_notes: Optional[str] = None


class PlanActivationResponse(BaseModel):
    """
    Authoritative response after plan approval and activation.
    """
    success: bool
    plan_id: str
    version: int
    status: str
    previous_plan_id: Optional[str] = None
    previous_version: Optional[int] = None
    activated_at: datetime
    officer_id: str
    officer_name: str
    message: str

