import pytest
import io
import uuid
from httpx import AsyncClient
from app.db.mongodb import get_database
from app.core.security import hash_otp


@pytest.mark.anyio
async def test_citizen_submit_without_otp_success(client: AsyncClient):
    """
    1. Citizen can submit without OTP.
    5. No OTP API is required for report submission.
    6. Report successfully persists to MongoDB.
    7. Phone is stored as unverified (phone_verified == False).
    8. Real location/address remains persisted.
    10. Report ID is generated by backend (RES-XXXXXXXX).
    """
    phone = f"987{uuid.uuid4().int % 10000000:07d}"
    lat = 28.5 + (uuid.uuid4().int % 50000) / 1000.0
    lon = 77.3 + (uuid.uuid4().int % 50000) / 1000.0
    
    payload = {
        "full_name": "Elena Rostova",
        "phone": phone,
        "emergency_type": "Medical Emergency",
        "description": "Individual experiencing severe cardiac distress near north wing entrance.",
        "location": {
            "latitude": lat,
            "longitude": lon,
            "address": "Sector 62, Institutional Area",
            "manual_zone": "East Sector",
            "accuracy_meters": 4.5,
        },
        "media": []
    }

    # Submit without any verification token or OTP call
    res = await client.post("/api/v1/citizen/reports", json=payload)
    assert res.status_code == 201
    report_data = res.json()

    # Verify ID structure: RES-XXXXXXXX
    report_id = report_data["report_id"]
    assert report_id.startswith("RES-")
    assert len(report_id) == 12

    assert report_data["citizen_name"] == "Elena Rostova"
    assert report_data["citizen_phone"] == phone
    assert report_data["emergency_type"] == "Medical Emergency"
    assert report_data["status"] == "RECEIVED"
    
    # Phone must NOT be marked as verified
    assert report_data["phone_verified"] is False
    assert report_data["possible_duplicate"] is False
    assert report_data["risk_level"] == "LOW"

    # Location must be persisted
    assert report_data["location"]["latitude"] == lat
    assert report_data["location"]["longitude"] == lon

    # Verify document in MongoDB
    db = get_database()
    doc = await db["citizen_reports"].find_one({"report_id": report_id})
    assert doc is not None
    assert doc["citizen_name"] == "Elena Rostova"
    assert doc["phone_verified"] is False

    # Check citizen_identities collection: unverified phone recorded correctly
    citizen = await db["citizen_identities"].find_one({"phone": phone})
    assert citizen is not None
    assert citizen["phone_verified"] is False


@pytest.mark.anyio
async def test_citizen_report_validations(client: AsyncClient):
    """
    2. Name is required.
    3. Phone is required.
    4. Invalid phone is rejected.
    """
    valid_loc = {"latitude": 28.6139, "longitude": 77.2090}
    valid_desc = "Emergency situation requiring immediate assistance on main avenue."

    # 2a. Missing name rejected
    res_no_name = await client.post("/api/v1/citizen/reports", json={
        "full_name": " ",
        "phone": "9876543210",
        "emergency_type": "Fire",
        "description": valid_desc,
        "location": valid_loc,
    })
    assert res_no_name.status_code in [400, 422]

    # 3a. Missing phone rejected
    res_no_phone = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Valid Citizen",
        "phone": " ",
        "emergency_type": "Fire",
        "description": valid_desc,
        "location": valid_loc,
    })
    assert res_no_phone.status_code in [400, 422]

    # 4a. Invalid phone format rejected
    res_bad_phone = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Valid Citizen",
        "phone": "not-a-phone-num",
        "emergency_type": "Fire",
        "description": valid_desc,
        "location": valid_loc,
    })
    assert res_bad_phone.status_code == 400
    assert "valid phone number" in res_bad_phone.json()["detail"].lower()

    # 4b. Too short phone rejected
    res_short_phone = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Valid Citizen",
        "phone": "123",
        "emergency_type": "Fire",
        "description": valid_desc,
        "location": valid_loc,
    })
    assert res_short_phone.status_code in [400, 422]


@pytest.mark.anyio
async def test_anti_bot_honeypot_protection(client: AsyncClient):
    """
    5. Anti-bot honeypot protection: automated bot submissions with filled honeypot are rejected.
    """
    phone = f"987{uuid.uuid4().int % 10000000:07d}"
    payload = {
        "full_name": "Spam Bot",
        "phone": phone,
        "emergency_type": "Other",
        "description": "Spam automated text content attempting to flood the platform.",
        "location": {"latitude": 28.6139, "longitude": 77.2090},
        "bot_honeypot": "http://spam-link.bot/automated",
    }

    res = await client.post("/api/v1/citizen/reports", json=payload)
    assert res.status_code == 400
    assert "Automated submission detected" in res.json()["detail"]


@pytest.mark.anyio
async def test_duplicate_detection_and_responder_visibility(client: AsyncClient):
    """
    12. Duplicate detection does not silently delete reports.
    13. Suspicious / duplicate reports can still reach responder review.
    """
    phone = f"987{uuid.uuid4().int % 10000000:07d}"
    lat = 19.0 + (uuid.uuid4().int % 50000) / 1000.0
    lon = 72.0 + (uuid.uuid4().int % 50000) / 1000.0
    coords = {"latitude": lat, "longitude": lon}

    # Report 1
    res1 = await client.post("/api/v1/citizen/reports", json={
        "full_name": "First Caller",
        "phone": phone,
        "emergency_type": "Fire",
        "description": "Large smoke plume visible on 3rd floor of commercial building.",
        "location": coords,
    })
    assert res1.status_code == 201
    rep1 = res1.json()
    assert rep1["possible_duplicate"] is False

    # Report 2 (Same emergency type, same phone/nearby location submitted right after)
    res2 = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Second Caller",
        "phone": phone,
        "emergency_type": "Fire",
        "description": "Fire spreading to adjacent unit on 3rd floor.",
        "location": coords,
    })
    assert res2.status_code == 201
    rep2 = res2.json()
    assert rep2["possible_duplicate"] is True
    assert rep2["risk_level"] in ["MEDIUM", "HIGH"]
    assert len(rep2["risk_reasons"]) > 0

    # Responder login and view reports list
    officer_login = await client.post(
        "/api/v1/auth/login",
        json={
            "phone": "9999999002",
            "password": "OfficerPassword@2026",
            "intended_role": "EMERGENCY_OFFICER",
        },
    )
    assert officer_login.status_code == 200
    token = officer_login.json()["access_token"]

    list_res = await client.get(
        "/api/v1/citizen/reports",
        headers={"Authorization": f"Bearer {token}"}
    )
    assert list_res.status_code == 200
    all_reports = list_res.json()
    
    # Both reports must exist and be accessible to responders (never silently dropped)
    report_ids = [r["report_id"] for r in all_reports]
    assert rep1["report_id"] in report_ids
    assert rep2["report_id"] in report_ids

    # Find rep2 in responder list and verify telemetry fields
    fetched_rep2 = next(r for r in all_reports if r["report_id"] == rep2["report_id"])
    assert fetched_rep2["possible_duplicate"] is True
    assert fetched_rep2["phone_verified"] is False
    assert fetched_rep2["risk_level"] in ["MEDIUM", "HIGH"]


@pytest.mark.anyio
async def test_citizen_media_upload_and_persistence(client: AsyncClient):
    """
    9. Real media remains persisted.
    """
    fake_png = io.BytesIO(b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01")
    files = {"file": ("incident_photo.png", fake_png, "image/png")}
    upload_res = await client.post("/api/v1/citizen/upload-media", files=files)
    assert upload_res.status_code == 200
    media_item = upload_res.json()
    assert media_item["media_type"] == "image/png"
    assert media_item["file_url"].startswith("/uploads/citizen_reports/")

    phone = f"987{uuid.uuid4().int % 10000000:07d}"
    report_res = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Media Citizen",
        "phone": phone,
        "emergency_type": "Road Accident",
        "description": "Multi-vehicle collision blocking highway intersection.",
        "location": {"latitude": 28.6139, "longitude": 77.2090},
        "media": [media_item],
    })
    assert report_res.status_code == 201
    rep_data = report_res.json()
    assert len(rep_data["media"]) == 1
    assert rep_data["media"][0]["filename"] == media_item["filename"]


@pytest.mark.anyio
async def test_optional_otp_functionality_preserved(client: AsyncClient):
    """
    14/15. Optional OTP functionality remains intact and functional without being mandatory for reports.
    """
    phone = f"987{uuid.uuid4().int % 10000000:07d}"
    
    # Send OTP
    send_res = await client.post("/api/v1/citizen/otp/send", json={"phone": phone, "name": "Jane Citizen"})
    assert send_res.status_code == 200

    # Verify with valid known OTP
    db = get_database()
    test_otp = "889900"
    otp_record = await db["citizen_otps"].find_one({"phone": phone, "is_used": False}, sort=[("created_at", -1), ("_id", -1)])
    await db["citizen_otps"].update_one(
        {"_id": otp_record["_id"]},
        {"$set": {"hashed_otp": hash_otp(test_otp), "attempts": 0}}
    )

    verify_res = await client.post("/api/v1/citizen/otp/verify", json={"phone": phone, "otp": test_otp})
    assert verify_res.status_code == 200
    verify_data = verify_res.json()
    assert "verification_token" in verify_data
    token = verify_data["verification_token"]

    # When submitted with legitimate verified token, phone_verified becomes True
    rep_res = await client.post("/api/v1/citizen/reports", json={
        "full_name": "Jane Citizen",
        "phone": phone,
        "emergency_type": "Flood",
        "description": "Water rising rapidly near drainage canal behind residential apartments.",
        "location": {"latitude": 28.6139, "longitude": 77.2090},
        "verification_token": token,
    })
    assert rep_res.status_code == 201
    assert rep_res.json()["phone_verified"] is True

